version: '3.8'
services:
  db:
    container_name: pg-fd
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: fd
    ports:
      - "5435:5432"